version: "3.9"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-pos-app:latest
    ports:
      - "8000:8000"
    volumes:
      - "data:/var/lib/postgresql/data"
      - "static:/static"
      - "media:/media"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/myprojectdb
      - SECRET_KEY=YOUR_SECRET_KEY
      - DEBUG=False
      - ALLOWED_HOSTS=*.example.com, 127.0.0.1, [::1]
      - LOGGING_CONFIG=production
  db:
    image: postgres:14
    volumes:
      - "data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myprojectdb
volumes:
  data:
  static:
  media: