name: CI/CD for PointOfSales

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  build-and-test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: python manage.py test
      - name: Run integration tests
        run: python manage.py test integration 
      - name: Run linting
        run: pylint myproject 
      - name: Build Docker image
        run: docker build -t jobet1995:latest .
      - name: Push Docker image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: jobet1995:latest
   

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to staging environment
        uses: terraform/setup-terraform@v2
        with:
          terraform_version: 1.4.0 
      - name: Initialize Terraform
        run: terraform init -backend-config="path=..."  
      - name: Apply Terraform changes
        run: terraform apply -auto-approve  
      - name: Deploy docker image to staging
        run: docker push my-pos-app:latest 
      - name: Update deployment configuration
        run: |
          kubectl apply -f k8s/staging.yaml 
          kubectl rollout restart deployment my-pos-app 

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: [build-and-test, deploy-to-staging]
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to production environment
        uses: terraform/setup-terraform@v2
        with:
          terraform_version: 1.4.0 
      - name: Initialize Terraform
        run: terraform init -backend-config="path=..."  
      - name: Apply Terraform changes
        run: terraform apply -auto-approve  
      - name: Deploy docker image to production
        run: docker push my-pos-app:latest 
      - name: Update deployment configuration
        run: |
          kubectl apply -f k8s/production.yaml 
          kubectl rollout restart deployment my-pos-app
